"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "../../../lib/supabase/client";
type OrderItem={id:string;display_name:string;position:number};type State={started:boolean;finished:boolean;current_pick:number;round_number:number;current_user_id:string|null;current_user_name:string|null;your_turn:boolean;player_order:OrderItem[];own_picks:string[];available_teams:string[];picked_count:number};type Pick={user_id:string;team_name:string;pick_number:number;round_number:number;created_at:string};type Participant={id:string;display_name:string};type Data={state:State;picks:Pick[]};type Rank={team_name:string;final_rank:number};
export default function AdminTeamsPage(){const supabase=createClient(),router=useRouter();const[data,setData]=useState<Data|null>(null),[participants,setParticipants]=useState<Participant[]>([]),[selected,setSelected]=useState(""),[ranks,setRanks]=useState<Record<string,string>>({}),[allowed,setAllowed]=useState(false),[message,setMessage]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}const{data:me}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(me?.role!=="admin"){router.replace("/dashboard");return}setAllowed(true);const[{data:d,error},{data:ps},{data:rk}]=await Promise.all([supabase.rpc("admin_team_draft_data"),supabase.from("profiles").select("id,display_name").order("display_name"),supabase.from("team_draft_final_ranks").select("team_name,final_rank")]);if(error)setMessage(error.message);else setData(d as Data);setParticipants((ps??[]) as Participant[]);setRanks(Object.fromEntries((rk??[]).map((r:Rank)=>[r.team_name,String(r.final_rank)])))}useEffect(()=>{load()},[]);
async function start(){if(!confirm("Провести новый жребий? Все текущие выборы будут сброшены."))return;const{data:d,error}=await supabase.rpc("start_team_draft");if(error)setMessage(error.message);else{setMessage("Жеребьевка проведена.");setData({state:d as State,picks:[]});await load()}}
async function reset(){if(!confirm("Полностью сбросить турнир «6 команд»? После этого нужно будет провести новый жребий."))return;const{error}=await supabase.rpc("reset_team_draft");setMessage(error?error.message:"Турнир сброшен.");await load()}
async function del(){if(!selected)return;const p=participants.find(x=>x.id===selected);if(!confirm(`Удалить последний выбор участника «${p?.display_name??""}»?`))return;const{error}=await supabase.rpc("admin_delete_last_team_pick",{p_user_id:selected});setMessage(error?error.message:`Последний выбор ${p?.display_name??"участника"} удалён.`);await load()}
async function rank(team:string){const n=Number(ranks[team]);if(!Number.isInteger(n)||n<1||n>36){setMessage("Место должно быть от 1 до 36.");return}const{error}=await supabase.rpc("admin_set_team_rank",{p_team_name:team,p_rank:n});setMessage(error?error.message:`Место команды ${team} сохранено.`)}
if(!allowed)return null;const state=data?.state,picks=data?.picks??[],total=(state?.player_order.length??0)*6,name=(id:string)=>state?.player_order.find(p=>p.id===id)?.display_name??participants.find(p=>p.id===id)?.display_name??"Участник";
return <main className="page"><div className="container"><header className="header"><div className="logo">ПРОГНОЗ<span>-ФРУНЗЕ</span></div><button className="text-button" onClick={()=>router.push("/teams")}>← К турниру</button></header><section className="card"><span className="eyebrow">Администрирование</span><h1>👕 Турнир «6 команд»</h1><p>Жеребьевка и контроль турнира. <b>Фактический результат матча вводится только один раз в основной панели «Прогнозы».</b> После этого он автоматически используется и здесь.</p><div className="top-actions" style={{marginTop:14}}><button className="cta" onClick={start}>🎲 Новый жребий</button><button className="text-button" onClick={reset}>Сбросить турнир</button></div>{message&&<p className="status-line">{message}</p>}</section>{state?.started&&<>
<section className="card" style={{marginTop:16}}><div className="section-heading"><div><h2>Порядок выбора</h2><p className="badge">Ход № {state.current_pick<=total?state.current_pick:"завершено"} · Раунд {Math.min(state.round_number,6)}/6</p></div><span className="badge">{state.picked_count}/{total}</span></div><div className="draft-order-grid">{state.player_order.map((p,i)=><div key={p.id} className={`draft-order-item ${p.id===state.current_user_id?"current":""}`}><span>{i+1}</span><b>{p.display_name}</b>{p.id===state.current_user_id&&<em>ХОД</em>}</div>)}</div></section>
<section className="card" style={{marginTop:16}}><h2>🛠 Управление последним выбором</h2><p className="badge">Можно удалить только последний выбор выбранного участника. Перед удалением требуется подтверждение.</p><div className="top-actions" style={{marginTop:14}}><select className="admin-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите участника</option>{participants.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><button className="text-button danger" disabled={!selected} onClick={del}>🗑 Удалить последний выбор</button></div></section>
<section className="card" style={{marginTop:16}}><h2>📋 Распределение команд</h2><div className="draft-table">{picks.map(p=><div className="draft-row" key={p.pick_number}><b>#{p.pick_number} · {name(p.user_id)}</b><span>{p.team_name}</span></div>)}</div></section>
<section className="card" style={{marginTop:16}}><h2>🏅 Итоговые места команд</h2><p className="badge">После лиговой фазы укажи места 1–36. Топ-8 автоматически получает +6 очков.</p><div className="rank-grid">{Array.from(new Set(picks.map(p=>p.team_name))).map(team=><div className="rank-row" key={team}><span>{team}</span><input inputMode="numeric" value={ranks[team]??""} onChange={e=>setRanks(x=>({...x,[team]:e.target.value}))} placeholder="место"/><button className="text-button" onClick={()=>rank(team)}>Сохранить</button></div>)}</div></section>
<section className="card" style={{marginTop:16}}><h2>⚽ Фактические результаты</h2><p>Здесь результаты <b>не вводятся</b>. Чтобы не дублировать работу, администратор вводит счёт один раз в <button className="text-button" onClick={()=>router.push("/admin")}>«Прогнозы → Матчи и результаты»</button>. Сохранённый результат автоматически попадёт в турнир «6 команд» и пересчитает его очки.</p></section>
</>}</div></main>}
