"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

type OrderItem={id:string;display_name:string;position:number};type DraftStatus={started:boolean;finished:boolean;current_pick:number;round_number:number;current_user_id:string|null;current_user_name:string|null;your_turn:boolean;player_order:OrderItem[];own_picks:string[];available_teams:string[];picked_count:number};type Pick={user_id:string;team_name:string;pick_number:number;round_number:number;created_at:string};type Participant={id:string;display_name:string};type Data={state:DraftStatus;picks:Pick[]};type Fixture={id:number;matchday:number;home_team:string;away_team:string;home_goals:number|null;away_goals:number|null;kickoff_date:string};type Extra={id:number;phase:string;match_date:string;home_team:string;away_team:string;home_goals:number|null;away_goals:number|null};

export default function AdminTeamsPage(){
 const supabase=createClient();const router=useRouter();const [data,setData]=useState<Data|null>(null);const [participants,setParticipants]=useState<Participant[]>([]);const [selectedParticipant,setSelectedParticipant]=useState("");const [fixtures,setFixtures]=useState<Fixture[]>([]);const [extra,setExtra]=useState<Extra[]>([]);const [ranks,setRanks]=useState<Record<string,string>>({});const [allowed,setAllowed]=useState(false);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [scores,setScores]=useState<Record<number,[string,string]>>({});
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return;}const {data:me}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(me?.role!=="admin"){router.replace("/dashboard");return;}setAllowed(true);const [{data:d,error},{data:ps},{data:fx},{data:ex},{data:rk}]=await Promise.all([supabase.rpc("admin_team_draft_data"),supabase.from("profiles").select("id,display_name").order("display_name"),supabase.from("team_draft_fixtures").select("id,matchday,home_team,away_team,home_goals,away_goals,kickoff_date").order("matchday").order("kickoff_date").order("id"),supabase.from("team_draft_extra_matches").select("*").order("match_date").order("id"),supabase.from("team_draft_final_ranks").select("team_name,final_rank")]);if(error)setMessage(error.message);else setData(d as Data);setParticipants((ps??[]) as Participant[]);const fs=(fx??[]) as Fixture[];setFixtures(fs);setScores(Object.fromEntries(fs.map(f=>[f.id,[f.home_goals===null?"":String(f.home_goals),f.away_goals===null?"":String(f.away_goals)]])));setExtra((ex??[]) as Extra[]);setRanks(Object.fromEntries((rk??[]).map((r:{team_name:string;final_rank:number})=>[r.team_name,String(r.final_rank)])));}
 useEffect(()=>{load();},[]);
 async function start(){if(!confirm("Провести новый жребий? Все текущие выборы будут сброшены."))return;setBusy(true);setMessage("");const {data:d,error}=await supabase.rpc("start_team_draft");setBusy(false);if(error)setMessage(error.message);else{setData({state:d as DraftStatus,picks:[]});setMessage("Жеребьевка проведена.");await load();}}
 async function reset(){if(!confirm("Полностью сбросить турнир «6 команд»? После этого нужно будет провести новый жребий."))return;setBusy(true);setMessage("");const {error}=await supabase.rpc("reset_team_draft");setBusy(false);if(error)setMessage(error.message);else{setMessage("Турнир сброшен.");await load();}}
 async function deleteLastPick(){if(!selectedParticipant)return;const participant=participants.find(p=>p.id===selectedParticipant);if(!confirm(`Удалить последний выбор участника «${participant?.display_name??""}»? Это действие нельзя отменить.`))return;setBusy(true);setMessage("");const {error}=await supabase.rpc("admin_delete_last_team_pick",{p_user_id:selectedParticipant});setBusy(false);if(error)setMessage(error.message);else{setMessage(`Последний выбор ${participant?.display_name??"участника"} удалён.`);await load();}}
 async function saveResult(id:number){const s=scores[id]??["",""];if(s[0]===""||s[1]===""){setMessage("Для сохранения результата укажите оба счёта.");return;}const h=Number(s[0]),a=Number(s[1]);if(!Number.isInteger(h)||!Number.isInteger(a)||h<0||a<0){setMessage("Счёт должен быть целым числом не меньше 0.");return;}setBusy(true);setMessage("");const {error}=await supabase.rpc("admin_set_team_result",{p_fixture_id:id,p_home_goals:h,p_away_goals:a});setBusy(false);if(error)setMessage(error.message);else{setMessage("Результат сохранён. Очки пересчитаны автоматически.");await load();}}
 async function saveRank(team:string){const n=Number(ranks[team]);if(!Number.isInteger(n)||n<1||n>36){setMessage("Место должно быть от 1 до 36.");return;}setBusy(true);const {error}=await supabase.rpc("admin_set_team_rank",{p_team_name:team,p_rank:n});setBusy(false);if(error)setMessage(error.message);else setMessage(`Место команды ${team} сохранено.`);}
 async function addExtra(){const form=document.getElementById("extra-form") as HTMLFormElement|null;if(!form)return;const fd=new FormData(form);const phase=String(fd.get("phase")||"").trim(),date=String(fd.get("date")||""),home=String(fd.get("home")||"").trim(),away=String(fd.get("away")||"").trim();const hg=Number(fd.get("hg")),ag=Number(fd.get("ag"));if(!phase||!date||!home||!away||!Number.isInteger(hg)||!Number.isInteger(ag)||hg<0||ag<0){setMessage("Заполните все поля плей-офф.");return;}setBusy(true);const {error}=await supabase.rpc("admin_add_team_match",{p_phase:phase,p_match_date:date,p_home_team:home,p_away_team:away,p_home_goals:hg,p_away_goals:ag});setBusy(false);if(error)setMessage(error.message);else{form.reset();setMessage("Матч плей-офф добавлен.");await load();}}
 if(!allowed)return null;const state=data?.state;const picks=data?.picks??[];const totalPicks=(state?.player_order.length??0)*6;const name=(id:string)=>state?.player_order.find(p=>p.id===id)?.display_name??participants.find(p=>p.id===id)?.display_name??"Участник";
 return <main className="page"><div className="container"><header className="header"><div className="logo">ПРОГНОЗ<span>-ФРУНЗЕ</span></div><button className="text-button" onClick={()=>router.push("/teams")}>← К турниру</button></header>
 <section className="card"><span className="eyebrow">Администрирование</span><h1>👕 Турнир «6 команд»</h1><p>Жеребьевка, отмена последнего выбора и управление реальными результатами турнира. После сохранения счёта база автоматически пересчитывает очки команд и участников.</p><div className="top-actions" style={{marginTop:14}}><button className="cta" disabled={busy} onClick={start}>🎲 Новый жребий</button><button className="text-button" disabled={busy} onClick={reset}>Сбросить турнир</button></div>{message&&<p className="status-line">{message}</p>}</section>
 {state?.started&&<>
 <section className="card" style={{marginTop:16}}><div className="section-heading"><div><h2>Порядок выбора</h2><p className="badge">Ход № {state.current_pick<=totalPicks?state.current_pick:"завершено"} · Раунд {Math.min(state.round_number,6)}/6</p></div><span className="badge">{state.picked_count}/{totalPicks}</span></div><div className="draft-order-grid">{state.player_order.map((p,i)=><div key={p.id} className={`draft-order-item ${p.id===state.current_user_id?"current":""}`}><span>{i+1}</span><b>{p.display_name}</b>{p.id===state.current_user_id&&<em>ХОД</em>}</div>)}</div></section>
 <section className="card" style={{marginTop:16}}><h2>Управление последним выбором</h2><p className="badge">Удаляется только самый последний выбор выбранного участника. Перед удалением требуется подтверждение.</p><div className="top-actions" style={{marginTop:14}}><select value={selectedParticipant} onChange={e=>setSelectedParticipant(e.target.value)} disabled={busy} className="admin-select"><option value="">Выберите участника</option>{participants.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><button className="text-button danger" disabled={busy||!selectedParticipant} onClick={deleteLastPick}>🗑 Удалить последний выбор</button></div></section>
 <section className="card" style={{marginTop:16}}><h2>📋 Кто какие команды выбрал</h2><div className="admin-pick-table">{picks.map(p=><div className="draft-row" key={p.pick_number}><b>#{p.pick_number} · {name(p.user_id)}</b><span>{p.team_name}</span></div>)}</div></section>
 <section className="card" style={{marginTop:16}}><div className="section-heading"><div><h2>⚽ Результаты матчей</h2><p className="badge">Вводи фактический счёт после каждой игры. Нажатие «Сохранить» сразу пересчитывает очки.</p></div><span className="badge">{fixtures.filter(f=>f.home_goals!==null).length}/{fixtures.length}</span></div><div className="admin-fixtures">{Array.from({length:8},(_,i)=>i+1).map(md=>{const list=fixtures.filter(f=>f.matchday===md);const done=list.filter(f=>f.home_goals!==null).length;return <details key={md} className="fixture-day" open={md===1}><summary><b>Тур {md}</b><span>{done}/{list.length}</span></summary><div className="admin-fixture-list">{list.map(f=>{const s=scores[f.id]??["",""];return <div className="admin-fixture-row" key={f.id}><div><small>{f.kickoff_date}</small><b>{f.home_team}</b></div><div className="admin-score"><input inputMode="numeric" value={s[0]} onChange={e=>setScores(x=>({...x,[f.id]:[e.target.value,s[1]]}))}/><span>:</span><input inputMode="numeric" value={s[1]} onChange={e=>setScores(x=>({...x,[f.id]:[s[0],e.target.value]}))}/><button className="text-button" disabled={busy||s[0]===""||s[1]===""} onClick={()=>saveResult(f.id)}>{f.home_goals===null?"Сохранить":"Изменить"}</button></div><div><small>&nbsp;</small><b>{f.away_team}</b></div></div>})}</div></details>})}</div></section>
 <section className="card" style={{marginTop:16}}><h2>🏅 Итоговые места команд</h2><p className="badge">После лиговой фазы укажи места 1–36. Командам из топ-8 автоматически добавится +6 очков.</p><div className="rank-grid">{Array.from(new Set(fixtures.flatMap(f=>[f.home_team,f.away_team]))).map(team=><div key={team} className="rank-row"><span>{team}</span><input inputMode="numeric" value={ranks[team]??""} onChange={e=>setRanks(x=>({...x,[team]:e.target.value}))} placeholder="место"/><button className="text-button" disabled={busy} onClick={()=>saveRank(team)}>Сохранить</button></div>)}</div></section>
 <section className="card" style={{marginTop:16}}><h2>🥇 Плей-офф / дополнительные матчи</h2><p className="badge">Здесь можно добавить матчи после лиговой фазы. Для них действуют обычные правила: победа +3, ничья +2, поражение 0, плюс учитываются голы и разница.</p><form id="extra-form" className="extra-form"><input name="phase" className="input" placeholder="Фаза, например 1/8 финала"/><input name="date" className="input" type="date"/><input name="home" className="input" placeholder="Хозяева"/><input name="away" className="input" placeholder="Гости"/><input name="hg" className="input" inputMode="numeric" placeholder="Голы хозяев"/><input name="ag" className="input" inputMode="numeric" placeholder="Голы гостей"/><button type="button" className="cta" disabled={busy} onClick={addExtra}>Добавить матч</button></form>{extra.length>0&&<div className="extra-list">{extra.map(m=><div className="admin-fixture-row" key={m.id}><span>{m.phase} · {m.match_date}</span><b>{m.home_team} {m.home_goals} : {m.away_goals} {m.away_team}</b></div>)}</div>}</section>
 <section className="card" style={{marginTop:16}}><h2>История выбора</h2><div className="draft-table">{picks.map(p=><div className="draft-row" key={p.pick_number}><b>#{p.pick_number} · {name(p.user_id)}</b><span>{p.team_name}</span></div>)}</div></section>
 </>}
 </div></main>;
}
